version: '3.8'
services:
  mongodb:
    image: mongo
  backend:
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend